// <auto-generated />
namespace SafriSoftv1._3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class safridbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(safridbcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "202202012052127_safridbcontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
